apiVersion: v1
kind: Service
metadata:
  name: service-espace-collaborateur
  namespace: nvne
  labels:
    app: service-espace-collaborateur
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8081
  selector:
    app: service-espace-collaborateur
  type: NodePort